### PR TITLE
Embedding mem fix

### PR DESCRIPTION
**Pull request by qubixes**
Added an aggregator process to prevent using too much memory. Memory usage slowed down loading the full embedding matrix a great deal.

### CODE REVIEW

**Comment by J535D165** [comment]
Thanks for the quick PR. Can you provide a benchmark (using `timeit`) for load_embedding with and without vocabulary?

**Comment by J535D165** [comment]
#9 #27

**Comment by qubixes** [comment]
I don't know how to easily do a timing with the vocabulary/index, but I have run it for the full one:

``` bash
#!/bin/bash

time python << EOF_PY

from timeit import default_timer as timer
from asr import load_embedding

start = timer()
x = load_embedding("../wiki.en.vec", n_jobs=1, verbose=True)
end = timer()
print(end-start)

EOF_PY

time python << EOF_PY

from timeit import default_timer as timer
from asr import load_embedding

start = timer()
x = load_embedding("../wiki.en.vec", n_jobs=6, verbose=True)
end = timer()
print(end-start)

EOF_PY
```

Output:

----------------------------------------------
Reading 2519370 vectors with 300 dimensions.
Found 2519370 word vectors.
276.64790950399765

real	4m52.106s
user	5m8.645s
sys	0m41.747s
-----------------------------------------------
-----------------------------------------------
Reading 2519370 vectors with 300 dimensions.
Found 2519370 word vectors.
95.74964433399145

real	1m57.146s
user	9m26.305s
sys	1m1.783s
------------------------------------------------

**Comment by qubixes** [comment]
After putting a sys.exit() just after loading the embedding and setting n_jobs to 4:

```bash
time python -m asr simulate --embedding ../wiki.en.vec ../data/datasets/ptsd_review/schoot-lgmm-ptsd.csv 
```

----------------------------------------------
Start review in 'simulate' mode.
Reading 2519370 vectors with 300 dimensions.
Found 16584 word vectors.

real	0m41.077s
user	1m36.311s
sys	0m18.005s
------------------------------------------------

**Comment by qubixes** [comment]
Okay, so I tried with try/except, and it doesn't find any ValueError's. Also, it's 4 times as slow that way, so I won't commit it.

I think I have an idea how it might work? Arabic is written from right to left, no? So maybe that's why all the minus signs are *after* the numbers... And it also makes sense that the name is not on the "first" column, at least for us Europeans... It doesn't make sense to me that it's not at the complete end, but I suppose it could be that half the row is right to left, and the other half left to right... Talk about confusing!

Anyway, I think there should be no issue, so you can merge the pull request.

**Comment by J535D165** [comment]
``` python
In [1]: import asr                                                                                                          

In [2]: %timeit asr.load_embedding("/Users/jonathan/asr_data/fasttext.cc.en.300.vec", n_jobs=6)                             
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
38.8 s ± 912 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [4]: %timeit asr.load_embedding("/Users/jonathan/asr_data/fasttext.cc.en.300.vec", n_jobs=1)                             
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
Reading 2000000 vectors with 300 dimensions.
Found 2000000 word vectors.
1min 47s ± 1.09 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Pull request merged**
