### PR TITLE
Max sampling

### PR DESCRIPTION
**Pull request by qubixes**
A big pull request with several changes/improvements:

* Add option to allow unknown (but frequent) words in de embedding matrix.
** Fix embedding test to reflect these changes.
* Implemented max sampling: select samples with the highest prediction probability.
* More logging:
** Start/end time
** Global settings
** Model parameters
** Fit parameters
* Add more configuration options through a config file, exposed to the CLI.
* Use recurrent dropout for the LSTM model.

### CODE REVIEW

**Comment by qubixes** [comment]
I will go through the code and write some more documentation/comments.

**Comment by J535D165** [comment]
Nice! Thumbs up for the max sampling implementation ;) 

About the config file, are you familiar with https://machinelearningmastery.com/save-load-keras-deep-learning-models/? This might be great for our CLI. It gives the user the option to tweak the NN model without using the API. 

Looking forward to merge this one!

**Comment by qubixes** [comment]
> Nice! Thumbs up for the max sampling implementation ;)
> 
> About the config file, are you familiar with https://machinelearningmastery.com/save-load-keras-deep-learning-models/? This might be great for our CLI. It gives the user the option to tweak the NN model without using the API.
> 
> Looking forward to merge this one!

It could be interesting in the long run, I agree. For input, perhaps we could build some kind of plugin system, where they could install/supply a python file that defines the architecture/model? For logging purposes it might be nice also to be able to reproduce the exact network from a save file.

**Comment by qubixes** [comment]
Okay, I rebased the pull request (removed my changes). Also did a test run to find myself another bug that has been fixed now.

**Pull request merged**
